baseURL = "https://www.joejean.net"
languageCode = "en-us"
title = "Joe Jean | Software Engineer"
theme = "joe-blog"
paginate = 6
disqusShortname = "joejeanblog"
buildDrafts = false

googleAnalytics ="UA-46696882-1"

[params]
	author = "Joe Jean"
	description = "Joe Jean | Software Engineer"

[menu]

  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-road'></i>"
    url = "/projects/"
    weight = 3

[permalinks]
  articles = "/:section/:slug/"
